let data = {
  capitals: {
    name: "CAPITALS",
    logo: "/assets/teams/capitals.png",
    cardColor: "#b9251c",
    mentor: "Mr. Sanjay Senma",
    captain: {
      name: "Harsh Rami",
      img: "/assets/players/capitals/Harshrami.png",
      course: "Software Development",
      sem: "4",
    },
    vcaptain: {
      name: "Hitarth Patel",
      img: "/assets/players/capitals/HitarthPatel.png",
      course: "Software development",
      sem: "4",
    },
    sponsor: "NUMA DC",
    players: [
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
    ],
  },
  indians: {
    name: "Indians",
    logo: "/assets/teams/Indians.png",
    cardColor: "#2d6ab1",
    mentor: "Mr. Ashish Pandya",
    captain: {
      name: "Krish Agrawal",
      img: "/assets/players/indians/KrishAgrawal.png",
      course: "Data management",
      sem: "6",
    },
    vcaptain: {
      name: "Tushar Panchal",
      img: "/assets/players/indians/TusharPanchal.png",
      course: "Data management",
      sem: "6",
    },
    sponsor: "NUMA DC",
    players: [
      { img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala", sem: "4" },
    ],
  },
  Kings_XI: {
    name: "Indians",
    logo: "/assets/teams/Kings_XI.png",
    cardColor: "#d71920",
    mentor: "Mr. Apurva Patel",
    captain: {
      name: "Viral Devmorari",
      img: "/assets/players/kings/DevmorariViral.png",
      course: "Game Design And Development",
      sem: "6",
    },
    vcaptain: {
      name: "Nisharg Thummar",
      img: "/assets/players/kings/Nishargthummar.png",
      course: "Data management",
      sem: "4",
    },
    sponsor: "NUMA DC",
    players: [{ img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala" }],
  },
  KnightRiders: {
    name: "KNIGHT RIDERS",
    logo: "/assets/teams/Knight_Riders.png",
    cardColor: "#ecc542",
    mentor: "Mr. Akshesh Prajapati",
    captain: {
      name: "Ovesh Shaikh",
      img: "/assets/players/knight_riders/OveshShaikh.png",
      course: "IMBA FINANCIAL SERVICE",
      sem: "2",
    },
    vcaptain: {
      name: "Mehandi Ali",
      img: "/assets/players/knight_riders/MahediAli.png",
      course: "Animation VFX",
      sem: "4",
    },
    sponsor: "NUMA DC",
    players: [{ img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala" }],
  },
  Royal_Challengers: {
    name: "Royal Challengers",
    logo: "/assets/teams/Royal_Challengers.png",
    cardColor: "#2b2a29",
    mentor: "Mr. Smit Koradia",
    captain: {
      name: "Rajveersinh Vaghela",
      img: "/assets/players/royal_challengers/RajveersinhVaghela.png",
      course: "Game Design And Development",
      sem: "6",
    },
    vcaptain: {
      name: "Dhavalsinh Chavda",
      img: "/assets/players/royal_challengers/ChavdaDhavalsinh .png",
      course: "Game Design And Development",
      sem: "6",
    },
    sponsor: "NUMA DC",
    players: [{ img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala" }],
  },
  Royals: {
    name: "Royals",
    logo: "/assets/teams/Royals.png",
    cardColor: "#eb83b5",
    mentor: "Mr. Bimlesh Badajena",
    captain: {
      name: "Harshil Sapariya",
      img: "/assets/players/royals/HarshilSapariya.png",
      course: "ITIMS & Cyber security",
      sem: "6",
    },
    vcaptain: {
      name: "Vatsal Dave",
      img: "/assets/players/royals/VastalDave.png",
      course: "ITIMS & Cyber security",
      sem: "6",
    },
    sponsor: "NUMA DC",
    players: [{ img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala" }],
  },
  Sunrisers: {
    name: "Sunrisers",
    logo: "/assets/teams/Sunrisers.png",
    cardColor: "#f26522",
    mentor: "Mr. Priyanka Goswami",
    captain: {
      name: "Manav Brahmabhatt",
      img: "/assets/players/sunrisers/ManavBrahmabhatt.png",
      course: "Cloud and App development",
      sem: "2",
    },
    vcaptain: {
      name: "Nigam Nai",
      img: "/assets/players/sunrisers/NigamNai.png",
      course: "Cloud and App development",
      sem: "2",
    },
    sponsor: "NUMA DC",
    players: [{ img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala" }],
  },
  Super_giants: {
    name: "Super Giants",
    logo: "/assets/teams/Super_giants.png",
    cardColor: "#ffffff",
    mentor: "Mr. Ashok Vestiya",
    captain: {
      name: "Devarsh Shah",
      img: "/assets/players/super_giants/DevarshShah.png",
      course: "ITIMS & Cyber security",
      sem: "6",
    },
    vcaptain: {
      name: "Harshal Shah",
      img: "/assets/players/super_giants/harshalShah.png",
      course: "B.Design interior",
      sem: "6",
    },
    sponsor: "NUMA DC",
    players: [{ img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala" }],
  },
  Super_Kings: {
    name: "Super Kings",
    logo: "/assets/teams/Super_Kings.png",
    cardColor: "#ffcb05",
    mentor: "Mr. Amit Mathur",
    captain: {
      name: "Sahil Rathod",
      img: "/assets/players/super_kings/Sahilrathod.png",
      course: "Cloud and app development",
      sem: "6",
    },
    vcaptain: {
      name: "Sahil Shaikh",
      img: "/assets/players/super_kings/SahilShaikh.png",
      course: "Cloud and app development",
      sem: "6",
    },
    sponsor: "NUMA DC",
    players: [{ img: "Aadil Rushnaiwala.png", name: "Aadil Rushnaiwala" }],
  },
  Titans: {
    name: "Titans",
    logo: "/assets/teams/Titans.png",
    cardColor: "#77c7f2",
    mentor: "Mr. Ravi Zala",
    captain: {
      name: "Vivek Gohil",
      img: "/assets/players/titans/vivekGohel.png",
      course: "ITIMS & Cyber security",
      sem: "4",
    },
    vcaptain: {
      name: "Karan Sakariya",
      img: "/assets/players/titans/KaranSakaraya.png",
      course: "IMBA FINANCIAL SERVICE",
      sem: "4",
    },
    sponsor: "NUMA DC",
    players: [
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
      {
        img: "/assets/players/titans/vivekGohel.png",
        name: "Aadil Rushnaiwala",
        course: "Software sem 3",
      },
    ],
  },
};

export default data;
